controller:

    # Replaces the default nginx-controller image with a custom image that contains the Signal Sciences nginx Module
    image:
      repository: myregistry/sigsci-module-nginx-ingress
      tag: "0.18.0"
      pullPolicy: IfNotPresent

    # Loads a custom nginx template with the Signal Sciences Lua directives included 
    customTemplate:
      configMapName: "sigsci-nginx-template"
      configMapKey: "nginx.tmpl"

    # Loads sidecar container image that houses the Signal Sciences Agent
    extraContainers:
      - name: sigsci-agent
        image: myregistry/sigsci-agent:latest
        imagepullPolicy: IfNotPresent
        volumeMounts:
        - name: sigsci-socket
          mountPath: /var/run

        # Sets Signal Sciences Agent keys
        env:
        - name: SIGSCI_ACCESSKEYID
          value: SETME
        - name: SIGSCI_SECRETACCESSKEY
          value: SETME

    # Mounts shared volume for sigsci.sock file
    extraVolumeMounts:
      - name: sigsci-socket
        mountPath: /var/run

    extraVolumes:
      - name: sigsci-socket
        emptyDir: {}
